apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - service-honcho-api-proxy.yaml
  - endpoints-honcho-api-proxy.yaml
  - middleware-honcho-api-strip.yaml
  - ingress-honcho-api-proxy.yaml
  - ingress.yaml